### ISSUE TITLE
GraphicSVG.elm out of date

### ISSUE THREAD

**Issue by emilyhorsman** [JacksYou/cs-1jc3-2016#1]
The version of `GraphicSVG.elm` is out of date as of `ebee97`.

The official up-to-date repo and documentation are at the links below:

https://github.com/MacCASOutreach/graphicsvg

http://package.elm-lang.org/packages/MacCASOutreach/graphicsvg/

**Comment by jmesyou** [comment]
updated as of 83f3b7d299af32a5d481f8959a03f6c4c1b6197f

**Comment by emilyhorsman** [comment]
Is it wise for this repo to maintain a mirror of the module? It would be possible to add the package to `elm-package.json` now

**Comment by jmesyou** [comment]
I think it's alright, if students would like to view source, they can directly do it here. I will not be updating gsvg to match the outreach repo if the current version is stable for course needs.
